"""Add resumes table

Revision ID: 66ae62784d5c
Revises: 
Create Date: 2026-09-25 15:17:52.034915

"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ae62784d5c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    existing = [] if context.is_offline_mode() else sa.inspect(op.get_bind()).get_table_names()

    if 'resumes' not in existing:
        op.create_table('resumes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('candidate_id', sa.UUID(), nullable=True),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('stored_filename', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('file_type', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('candidate_id'),
        sa.UniqueConstraint('stored_filename')
        )
        op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)

    if not context.is_offline_mode() and 'candidates' in existing:
        cols = [c['name'] for c in sa.inspect(op.get_bind()).get_columns('candidates')]
        if 'resume_id' in cols:
            op.drop_column('candidates', 'resume_id')
        if 'resume_file_name' in cols:
            op.drop_column('candidates', 'resume_file_name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('resume_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
