"""Add rich verification fields to resume validation report

Revision ID: b085b818da74
Revises: 29a5aca6b58b
Create Date: 2026-09-28 21:21:19.101154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b085b818da74'
down_revision: Union[str, Sequence[str], None] = '29a5aca6b58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_validation_reports', sa.Column('verification_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('resume_validation_reports', sa.Column('validation_pipeline', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('resume_validation_reports', sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('resume_validation_reports', sa.Column('inconsistencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('resume_validation_reports', sa.Column('missing_information', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('resume_validation_reports', sa.Column('github_verification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('resume_validation_reports', sa.Column('linkedin_verification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('resume_validation_reports', sa.Column('project_verification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_validation_reports', 'project_verification')
    op.drop_column('resume_validation_reports', 'linkedin_verification')
    op.drop_column('resume_validation_reports', 'github_verification')
    op.drop_column('resume_validation_reports', 'missing_information')
    op.drop_column('resume_validation_reports', 'inconsistencies')
    op.drop_column('resume_validation_reports', 'evidence')
    op.drop_column('resume_validation_reports', 'validation_pipeline')
    op.drop_column('resume_validation_reports', 'verification_summary')
    # ### end Alembic commands ###
